services:
  - type: web
    name: gpt-crypto-api
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NEWS_API_KEY
        sync: false
      - key: ETHERSCAN_API_KEY
        sync: false
      - key: BASESCAN_API_KEY
        sync: false
      - key: BSCSCAN_API_KEY
        sync: false
      - key: SOLANA_RPC_URL
        value: https://api.mainnet-beta.solana.com
      - key: XRP_RPC_URL
        value: https://s1.ripple.com:51234
      - key: LOG_LEVEL
        value: INFO
